In [2]:
import numpy as np
import matplotlib.pyplot as plt
import torch
import pandas as pd


In [3]:
#convert 2D list to 2D tensor
two_2D_list=[[11,12,13],[21,22,23],[33,34,35]]
two_2D_tensor=torch.tensor(two_2D_list)
print("the new tensor: ", two_2D_tensor)


the new tensor:  tensor([[11, 12, 13],
        [21, 22, 23],
        [33, 34, 35]])


In [5]:
print("The dimension of twoD_tensor: ", two_2D_tensor.ndimension())
print("The shape of twoD_tensor: ", two_2D_tensor.shape)
print("The shape of twoD_tensor: ", two_2D_tensor.size())
print("The number of elements in twoD_tensor: ", two_2D_tensor.numel())

The dimension of twoD_tensor:  2
The shape of twoD_tensor:  torch.Size([3, 3])
The shape of twoD_tensor:  torch.Size([3, 3])
The number of elements in twoD_tensor:  9


In [6]:
#convert tensor to numpy array
twoD_numpy=two_2D_tensor.numpy()
print("tensor-> Numpy array" )
print("The numpy array after converting: ", twoD_numpy)
print("Type after converting: ", twoD_numpy.dtype)
print("=======================================")
new_twoD_tensor = torch.from_numpy(twoD_numpy)
print("Numpy Array -> Tensor:")
print("The tensor after converting:", new_twoD_tensor)
print("Type after converting: ", new_twoD_tensor.dtype)

tensor-> Numpy array
The numpy array after converting:  [[11 12 13]
 [21 22 23]
 [33 34 35]]
Type after converting:  int64
Numpy Array -> Tensor:
The tensor after converting: tensor([[11, 12, 13],
        [21, 22, 23],
        [33, 34, 35]])
Type after converting:  torch.int64


In [7]:
#converting pandas dataframe to tensor
df=pd.DataFrame({'a':[11,21,31],'b':[12,22,2122]})
print("pandas dataframe to numpy:",df.values)
print("before converting: ",df.values.dtype)
print("===============================")
new_tensor=torch.from_numpy(df.values)
print("Tensor AFTER converting: ", new_tensor)
print("Type AFTER converting: ", new_tensor.dtype)

pandas dataframe to numpy: [[  11   12]
 [  21   22]
 [  31 2122]]
before converting:  int64
Tensor AFTER converting:  tensor([[  11,   12],
        [  21,   22],
        [  31, 2122]])
Type AFTER converting:  torch.int64


In [8]:
# Practice: try to convert Pandas Series to tensor

df = pd.DataFrame({'A':[11, 33, 22],'B':[3, 3, 2]})
new_tensor=torch.from_numpy(df.values)
print("Tensor AFTER converting: ", new_tensor)
print("Type AFTER converting: ", new_tensor.dtype)

Tensor AFTER converting:  tensor([[11,  3],
        [33,  3],
        [22,  2]])
Type AFTER converting:  torch.int64


In [10]:
#accessing the positions
tensor_example = torch.tensor([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
print("What is the value on 2nd-row 3rd-column? ", tensor_example[1, 2])
print("What is the value on 2nd-row 3rd-column? ", tensor_example[1][2])

What is the value on 2nd-row 3rd-column?  tensor(23)
What is the value on 2nd-row 3rd-column?  tensor(23)


In [11]:
#slicing in 2D tensors
tensor_example = torch.tensor([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
print("What is the value on 1st-row first two columns? ", tensor_example[0, 0:2])
print("What is the value on 1st-row first two columns? ", tensor_example[0][0:2])

What is the value on 1st-row first two columns?  tensor([11, 12])
What is the value on 1st-row first two columns?  tensor([11, 12])


In [14]:
tensor_example = torch.tensor([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
sliced_tensor_example = tensor_example[1:3]
print("1. Slicing step on tensor_example: ")
print("Result after tensor_example[1:3]: ", sliced_tensor_example)
print("Dimension after tensor_example[1:3]: ", sliced_tensor_example.ndimension())
print("================================================")
print("2. Pick an index on sliced_tensor_example: ")
print("Result after sliced_tensor_example[1]: ", sliced_tensor_example[1])
print("Dimension after sliced_tensor_example[1]: ", sliced_tensor_example[1].ndimension())
print("================================================")
print("3. Combine these step together:")
print("Result: ", tensor_example[1:3][1])
print("Dimension: ", tensor_example[1:3][1].ndimension())

1. Slicing step on tensor_example: 
Result after tensor_example[1:3]:  tensor([[21, 22, 23],
        [31, 32, 33]])
Dimension after tensor_example[1:3]:  2
2. Pick an index on sliced_tensor_example: 
Result after sliced_tensor_example[1]:  tensor([31, 32, 33])
Dimension after sliced_tensor_example[1]:  1
3. Combine these step together:
Result:  tensor([31, 32, 33])
Dimension:  1


In [15]:
#what is th value of last rows of 3rd columns
tensor_example=torch.tensor([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
print("What is the value on 3rd-column last two rows? ", tensor_example[1:3, 2])

What is the value on 3rd-column last two rows?  tensor([23, 33])


In [17]:
#changing the values on the second column and the lst two rooms to 0
tensor_ques = torch.tensor([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
tensor_ques[1:3,1]=0
print(tensor_ques)

tensor([[11, 12, 13],
        [21,  0, 23],
        [31,  0, 33]])


In [18]:
#adding tensors
# Calculate [[1, 0], [0, 1]] + [[2, 1], [1, 2]]

X = torch.tensor([[1, 0],[0, 1]]) 
Y = torch.tensor([[2, 1],[1, 2]])
X_plus_Y = X + Y

print("The result of X + Y: ", X_plus_Y)

The result of X + Y:  tensor([[3, 1],
        [1, 3]])


In [19]:
#scalar multiplication
# Calculate 2 * [[2, 1], [1, 2]]

Y = torch.tensor([[2, 1], [1, 2]]) 
two_Y = 2 * Y
print("The result of 2Y: ", two_Y)

The result of 2Y:  tensor([[4, 2],
        [2, 4]])


In [20]:
#Element-wise Product/Hadamard Product
X = torch.tensor([[1, 0], [0, 1]])
Y = torch.tensor([[2, 1], [1, 2]]) 
X_times_Y = X * Y
print("The result of X * Y: ", X_times_Y)

The result of X * Y:  tensor([[2, 0],
        [0, 2]])


In [21]:
#matrix multiplication
# Calculate [[0, 1, 1], [1, 0, 1]] * [[1, 1], [1, 1], [-1, 1]]

A = torch.tensor([[0, 1, 1], [1, 0, 1]])
B = torch.tensor([[1, 1], [1, 1], [-1, 1]])
A_times_B = torch.mm(A,B)
print("The result of A * B: ", A_times_B)

The result of A * B:  tensor([[0, 2],
        [0, 2]])
